name: ItemsBlocker
version: '${version}'
main: pl.flezy.itemsblocker.ItemsBlocker
api-version: '1.20'
authors: [Flezy]
permissions:
  itemsblocker.command:
    description: Permission to use plugin commands
    default: op
  itemsblocker.bypass:
    description: Permission to bypass items blocks
    default: op
