name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup gradle cache
        uses: burrunan/gradle-cache-action@v3
        with:
          save-generated-gradle-jars: false
          save-local-build-cache: false
          save-gradle-dependencies-cache: true
          save-maven-dependencies-cache: true
      - name: Build Project
        run: ./gradlew build
